import {
  Award, ArrowDown, ArrowLeft, ArrowRight, ArrowUp, ArrowUpRight, Bell, BookOpen, Bookmark, Brain, Briefcase, Building2,
  Calendar, CalendarCheck, Camera, ChartColumn, ChartLine, ChartPie, Check, CircleAlert, CircleCheck, CircleHelp, CircleX,
  ClipboardCheck, Clock, Coffee, Compass, Eye, FileText, Flag, Flame, Footprints, Gauge, Gift, Globe, GraduationCap,
  Handshake, Hash, Heart, HeartHandshake, Info, Key, Laptop, Layers, Leaf, Lightbulb, Link, ListChecks, Lock, LucideIcon,
  Mail, MapPin, Medal, Megaphone, MessageCircle, MessagesSquare, Mic, Mountain, PenLine, Phone, Plus, Puzzle, Quote,
  RefreshCw, Rocket, Search, Settings, ShieldCheck, Smartphone, Smile, Sparkles, Sprout, Star, Sun, Target, ThumbsUp,
  TrendingDown, TrendingUp, Trophy, User, UserRound, Users, Video, X, Zap,
} from 'lucide-react'

/**
 * 「요소」에서 넣을 수 있는 아이콘. 전체 아이콘 묶음을 불러오면 파일이 커지므로 카드뉴스에 자주 쓰는 것만 골랐다.
 * tags = 한글 검색어. 이름은 저장값이므로 바꾸지 말 것 (바꾸면 기존 페이지의 아이콘이 사라짐)
 */
export const iconSet: { name: string; Icon: LucideIcon; tags: string }[] = [
  { name: 'Users', Icon: Users, tags: '사람 팀 그룹 구성원 조직' },
  { name: 'User', Icon: User, tags: '사람 개인 리더' },
  { name: 'UserRound', Icon: UserRound, tags: '사람 프로필 인물' },
  { name: 'Handshake', Icon: Handshake, tags: '협력 파트너 계약 악수' },
  { name: 'HeartHandshake', Icon: HeartHandshake, tags: '신뢰 관계 협력 배려' },
  { name: 'MessageCircle', Icon: MessageCircle, tags: '대화 말풍선 피드백 소통' },
  { name: 'MessagesSquare', Icon: MessagesSquare, tags: '대화 토론 소통 회의' },
  { name: 'Megaphone', Icon: Megaphone, tags: '공지 알림 홍보 발표' },
  { name: 'Quote', Icon: Quote, tags: '인용 후기 말' },
  { name: 'Mic', Icon: Mic, tags: '인터뷰 발표 강연' },
  { name: 'Lightbulb', Icon: Lightbulb, tags: '아이디어 인사이트 전구 생각' },
  { name: 'Brain', Icon: Brain, tags: '생각 뇌 인지 학습' },
  { name: 'Target', Icon: Target, tags: '목표 과녁 타겟 성과' },
  { name: 'Flag', Icon: Flag, tags: '깃발 목표 시작 마일스톤' },
  { name: 'Rocket', Icon: Rocket, tags: '성장 시작 로켓 도전' },
  { name: 'Mountain', Icon: Mountain, tags: '도전 목표 산 극복' },
  { name: 'Footprints', Icon: Footprints, tags: '발자국 과정 단계 여정' },
  { name: 'Compass', Icon: Compass, tags: '방향 나침반 전략 비전' },
  { name: 'TrendingUp', Icon: TrendingUp, tags: '상승 성장 증가 그래프' },
  { name: 'TrendingDown', Icon: TrendingDown, tags: '하락 감소 그래프' },
  { name: 'ChartColumn', Icon: ChartColumn, tags: '차트 막대 데이터 통계' },
  { name: 'ChartLine', Icon: ChartLine, tags: '차트 선 추이 데이터' },
  { name: 'ChartPie', Icon: ChartPie, tags: '차트 원 비율 데이터' },
  { name: 'Gauge', Icon: Gauge, tags: '게이지 진단 측정 점수' },
  { name: 'Award', Icon: Award, tags: '상 수상 인증 배지' },
  { name: 'Trophy', Icon: Trophy, tags: '트로피 우승 성과' },
  { name: 'Medal', Icon: Medal, tags: '메달 수상 성과' },
  { name: 'Star', Icon: Star, tags: '별 중요 추천 평점' },
  { name: 'Heart', Icon: Heart, tags: '하트 좋아요 마음 감사' },
  { name: 'ThumbsUp', Icon: ThumbsUp, tags: '좋아요 칭찬 추천' },
  { name: 'Smile', Icon: Smile, tags: '웃음 만족 행복 감정' },
  { name: 'Sparkles', Icon: Sparkles, tags: '반짝 강조 특별 새로운' },
  { name: 'Zap', Icon: Zap, tags: '번개 빠른 에너지 핵심' },
  { name: 'Flame', Icon: Flame, tags: '불 열정 인기' },
  { name: 'BookOpen', Icon: BookOpen, tags: '책 학습 교육 독서' },
  { name: 'GraduationCap', Icon: GraduationCap, tags: '교육 학습 졸업 과정' },
  { name: 'PenLine', Icon: PenLine, tags: '펜 작성 기록 쓰기' },
  { name: 'FileText', Icon: FileText, tags: '문서 보고서 자료' },
  { name: 'ClipboardCheck', Icon: ClipboardCheck, tags: '체크리스트 점검 진단' },
  { name: 'ListChecks', Icon: ListChecks, tags: '체크리스트 할일 목록' },
  { name: 'Briefcase', Icon: Briefcase, tags: '업무 직장 비즈니스 가방' },
  { name: 'Building2', Icon: Building2, tags: '회사 조직 건물 기업' },
  { name: 'Calendar', Icon: Calendar, tags: '일정 달력 날짜' },
  { name: 'CalendarCheck', Icon: CalendarCheck, tags: '일정 확인 예약 출석' },
  { name: 'Clock', Icon: Clock, tags: '시간 시계 마감' },
  { name: 'Mail', Icon: Mail, tags: '메일 편지 연락 뉴스레터' },
  { name: 'Phone', Icon: Phone, tags: '전화 연락 문의' },
  { name: 'MapPin', Icon: MapPin, tags: '장소 위치 지도' },
  { name: 'Globe', Icon: Globe, tags: '세계 글로벌 웹' },
  { name: 'Link', Icon: Link, tags: '링크 연결' },
  { name: 'Laptop', Icon: Laptop, tags: '노트북 온라인 디지털' },
  { name: 'Smartphone', Icon: Smartphone, tags: '휴대폰 모바일 앱' },
  { name: 'Video', Icon: Video, tags: '영상 비디오 온라인' },
  { name: 'Camera', Icon: Camera, tags: '카메라 사진 촬영' },
  { name: 'Search', Icon: Search, tags: '검색 찾기 돋보기 분석' },
  { name: 'Eye', Icon: Eye, tags: '보기 관찰 시선' },
  { name: 'Settings', Icon: Settings, tags: '설정 톱니 시스템 운영' },
  { name: 'Puzzle', Icon: Puzzle, tags: '퍼즐 문제해결 조각 역량' },
  { name: 'Layers', Icon: Layers, tags: '레이어 단계 구조 층' },
  { name: 'RefreshCw', Icon: RefreshCw, tags: '순환 반복 새로고침 변화' },
  { name: 'Key', Icon: Key, tags: '열쇠 핵심 비결' },
  { name: 'Lock', Icon: Lock, tags: '자물쇠 보안' },
  { name: 'ShieldCheck', Icon: ShieldCheck, tags: '안전 보호 신뢰 심리적' },
  { name: 'Bell', Icon: Bell, tags: '알림 종 공지' },
  { name: 'Bookmark', Icon: Bookmark, tags: '저장 북마크' },
  { name: 'Gift', Icon: Gift, tags: '선물 이벤트 혜택' },
  { name: 'Coffee', Icon: Coffee, tags: '커피 휴식 티타임 대화' },
  { name: 'Sun', Icon: Sun, tags: '해 긍정 아침 에너지' },
  { name: 'Leaf', Icon: Leaf, tags: '잎 성장 자연 환경' },
  { name: 'Sprout', Icon: Sprout, tags: '새싹 성장 신입 시작' },
  { name: 'Hash', Icon: Hash, tags: '해시태그 키워드 샵' },
  { name: 'Info', Icon: Info, tags: '정보 안내' },
  { name: 'CircleHelp', Icon: CircleHelp, tags: '질문 물음표 궁금' },
  { name: 'CircleAlert', Icon: CircleAlert, tags: '주의 경고 느낌표' },
  { name: 'CircleCheck', Icon: CircleCheck, tags: '체크 완료 정답 확인' },
  { name: 'CircleX', Icon: CircleX, tags: '엑스 오답 금지 취소' },
  { name: 'Check', Icon: Check, tags: '체크 확인 완료' },
  { name: 'X', Icon: X, tags: '엑스 아니오 금지' },
  { name: 'Plus', Icon: Plus, tags: '더하기 추가 플러스' },
  { name: 'ArrowRight', Icon: ArrowRight, tags: '화살표 오른쪽 다음' },
  { name: 'ArrowLeft', Icon: ArrowLeft, tags: '화살표 왼쪽 이전' },
  { name: 'ArrowUp', Icon: ArrowUp, tags: '화살표 위 상승' },
  { name: 'ArrowDown', Icon: ArrowDown, tags: '화살표 아래 하락' },
  { name: 'ArrowUpRight', Icon: ArrowUpRight, tags: '화살표 대각선 링크 이동' },
]

export const iconMap: Record<string, LucideIcon> = Object.fromEntries(iconSet.map(({ name, Icon }) => [name, Icon]))
